[gta22] Fixed artifact upliading and added skipped tags for XML files and improved counting abstraction

diff --git a/test b/test
--- a/test
+++ b/test
@@ -3,81 +3,72 @@
 # Script which tests the compiler against all test programs in exampleProgs
 
 # test_compile ($1 == file, $2 == expected code, )
-# Attempts to compile a program and compares the exit code
+# Checks if the file it to be combiled and 
+# Attempts to compileit and compares the exit code
 # to the expected. Saves the results in temp
 test_compile () {
-  ./compile $1
-  code=$?
-  if [ $code -eq $2 ]
+  if [[ $file == \'* ]]
   then
-    printf "<testcase name=\"$1\" />\n" >> temp
-  else
-    printf "<testcase name=\"$1\" >\n" >> temp
-    printf "<failure message=\"Expected exit code = 200, got $code\" type=\"FAIL\" />\n" >> temp
+    echo "*** SKIPING TEST ${1:1}"
+    printf "<testcase name=\"${1:1}\" >\n" >> temp
+    printf "<skipped message=\"The program ${1:1} has been skipped\"/>\n" >> temp
     printf "</testcase>\n" >> temp
+  else
+    ./compile $1
+    code=$?
+    if [ $code -eq $2 ]
+    then
+      printf "<testcase name=\"$1\" />\n" >> temp
+    else
+      printf "<testcase name=\"$1\" >\n" >> temp
+      printf "<failure message=\"Expected exit code = $2, got $code\" type=\"FAIL\" />\n" >> temp
+      printf "</testcase>\n" >> temp
+    fi
   fi
 }
 
-# count_results ($1 == testsuite_name, $2 == num_skipped_tests, $3 == results_file)
+# count_results ($1 == testsuite_name, $2 == results_file)
 # Counts how many test cases have failed and stores the results in 
 # results_file
 count_results () {
   fails=$(cat temp | grep -E "(FAIL)" | wc -l)
   tests=$(cat temp | grep -E "testcase name=" | wc -l)
-  printf "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" > $3
-  printf "<testsuite name=\"Programs at: $1\" tests=\"$tests\" failures=\"$fails\"  skipped=\"$2\">\n" >> $3
-  cat temp >> $3
-  printf "</testsuite>\n" >> $3
+  skipped=$(cat temp | grep -E "skipped" | wc -l)
+  printf "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\n" > $2
+  printf "<testsuite name=\"Programs at: $1\" tests=\"$tests\" failures=\"$fails\"  skipped=\"$skipped\">\n" >> $2
+  cat temp >> $2
+  printf "</testsuite>\n" >> $2
 }
 
 
 # Test results for valid tests
 
-
 fileLs=$(cat exampleProgs/valid.selection | tr " " "\n")
-skipped=0
 printf "" > temp
 for file in $fileLs
 do
-  if [[ $file == \'* ]]
-  then
-    skipped=$((skipped + 1))
-  else
-    test_compile $file 0
-  fi
+  test_compile $file 0
 done
-count_results "valid folder" $skipped "validRes.xml"
+count_results "valid folder" "validRes.xml"
 
 # Test result for syntax errors
 
 fileLs=$(cat exampleProgs/syntax.selection | tr " " "\n")
-skipped=0
 printf "" > temp
 for file in $fileLs
 do
-  if [[ $file == \'* ]]
-  then
-    skipped=$((skipped + 1))
-  else
-    test_compile $file 100
-  fi
+  test_compile $file 100
 done
-count_results "syntax folder" $skipped "syntaxRes.xml"
+count_results "syntax folder" "syntaxRes.xml"
 
 # Test result for semantic errors
 
 fileLs=$(cat exampleProgs/semantic.selection | tr " " "\n")
-skipped=0
 printf "" > temp
 for file in $fileLs
 do
-  if [[ $file == \'* ]]
-  then
-    skipped=$((skipped + 1))
-  else
-    test_compile $file 200 
-  fi
+  test_compile $file 200
 done
-count_results "semantic folder" $skipped "semanticRes.xml"
+count_results "semantic folder" "semanticRes.xml"
 
 rm temp
